name: Stage the App

on: 
  pull_request:
    types: [labeled]
    
env:
  DOCKER_IMAGE_NAME: bhavanakonchada-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: bhavanakonchada-ttt-app
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
